package main

import (
	"bufio"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
)

// --- 数据结构定义 ---

type Config struct {
	AdsWorkDir   string
	ProxyWorkDir string
	OutputDir    string
	CopyTo       string
	Verbose      bool
	ProxyGroups  []ProxyGroup
	AdsEntries   []string
	ManualAds    []string
	ManualProxy  ManualProxyConfig
}

type ProxyGroup struct {
	Name          string
	Subnet        string
	StartIP       string
	PerDomainIP   bool
	Entries       []ProxyEntry
}

type ProxyEntry struct {
	Tag      string
	Excludes []string
	ExcludeCN bool
}

type ManualProxyConfig struct {
	StartIP     string
	PerDomainIP bool
	Domains     []string
}

// --- 核心逻辑：IP 递增器 ---

func nextIP(ip net.IP) net.IP {
	next := make(net.IP, len(ip))
	copy(next, ip)
	for i := len(next) - 1; i >= 0; i-- {
		next[i]++
		if next[i] != 0 {
			break
		}
	}
	// 简单跳过 .0 和 .255 (针对 /24 习惯)
	if next[3] == 0 || next[3] == 255 {
		return nextIP(next)
	}
	return next
}

// --- 核心逻辑：Geosite 解析与排除 ---

func fetchAndNormalize(tag string, isAds bool, excludeCN bool) (map[string]bool, error) {
	url := fmt.Sprintf("https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/%s", tag)
	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	domains := make(map[string]bool)
	scanner := bufio.NewScanner(resp.Body)
	
	// 正则：提取指令前缀
	re := regexp.MustCompile(`^(domain:|full:|keyword:|regexp:)?([a-zA-Z0-9._-]+)`)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// 属性过滤逻辑
		hasAdsTag := strings.Contains(line, "@ad")
		hasCNTag := strings.Contains(line, "@cn")

		if isAds && !hasAdsTag {
			continue
		}
		if !isAds && hasAdsTag {
			continue
		}
		if !isAds && excludeCN && hasCNTag {
			continue
		}

		match := re.FindStringSubmatch(line)
		if len(match) > 2 {
			rawDomain := match[2]
			// 统一转换为通配符格式以适配 ADH
			domains["*."+strings.ToLower(rawDomain)] = true
		}
	}
	return domains, nil
}

// --- 主程序流 ---

func main() {
	fmt.Printf("[%s] 开始生成规则...\n", time.Now().Format("15:04:05"))

	// 1. 解析 rules.conf (简易解析示例)
	// 实际运行中建议使用专门的 ini 库，此处为演示核心逻辑
	cfg := Config{
		OutputDir: "./output",
		ProxyGroups: []ProxyGroup{
			{
				Name: "Google", StartIP: "198.19.0.1", PerDomainIP: true,
				Entries: []ProxyEntry{{Tag: "google", Excludes: []string{"google-gemini"}}},
			},
			// 更多分组可由此解析 rules.conf 填充...
		},
	}

	os.MkdirAll(cfg.OutputDir, 0755)
	
	// 2. 生成 Proxy 规则
	proxyFile, _ := os.Create(filepath.Join(cfg.OutputDir, "proxy-geosite.txt"))
	defer proxyFile.Close()
	ipMapFile, _ := os.Create(filepath.Join(cfg.OutputDir, "ip_map.txt"))
	defer ipMapFile.Close()

	var mu sync.Mutex
	fmt.Fprintln(proxyFile, "! Generated by Go Generator")

	for _, group := range cfg.ProxyGroups {
		fmt.Printf("处理分组: %s\n", group.Name)
		currentIP := net.ParseIP(group.StartIP).To4()

		for _, entry := range group.Entries {
			// 并发获取主域名和排除项 (此处简写)
			mainDomains, _ := fetchAndNormalize(entry.Tag, false, entry.ExcludeCN)
			
			// 排除逻辑：集合减法
			for _, exTag := range entry.Excludes {
				exDomains, _ := fetchAndNormalize(exTag, false, false)
				for d := range exDomains {
					delete(mainDomains, d)
				}
			}

			// 排序输出
			keys := make([]string, 0, len(mainDomains))
			for k := range mainDomains { keys = append(keys, k) }
			sort.Strings(keys)

			for _, d := range keys {
				fmt.Fprintf(proxyFile, "||%s^$dnsrewrite=NOERROR;A;%s\n", d, currentIP)
				fmt.Fprintf(ipMapFile, "%s %s\n", currentIP, d)
				if group.PerDomainIP {
					currentIP = nextIP(currentIP)
				}
			}
		}
	}

	fmt.Printf("[%s] 任务完成！产物已存入 output 目录。\n", time.Now().Format("15:04:05"))
}
